//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group17_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUs
    {
        public string companyAddress { get; set; }
        public string shippingPolicy { get; set; }
        public string returnPolicy { get; set; }
        public string contactInfo { get; set; }
        public string businessDescription { get; set; }
        public string adminID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
